Repository Himedia-bootcamp/MarketNawa.BE, pull requests merged in 2024-07, with the labels that each got.

#2 feat: elasticsearch api 협업을 위해 틀 만들기
  src/main/kotlin/marketnawa/be/ott/marketnawabe/config/ElasticsearchProperties.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/controller/SearchController.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/document/SortingOrder.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/service/SearchService.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/util/ElasticsearchUtil.kt
Labels: ⚙ Setting, ✨ Feature, 📬 API

#3 Feat: Elasticsearch api 기능 추가
  src/main/kotlin/marketnawa/be/ott/marketnawabe/controller/SearchController.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/service/SearchService.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/util/ElasticsearchUtil.kt
Labels: ⚙ Setting, 📬 API

#4 [Feat] : service controller
  src/main/kotlin/marketnawa/be/ott/marketnawabe/config/ElasticsearchConfig.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/controller/SearchController.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/document/MarketFood.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/dto/MarketFoodDTO.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/repository/FoodRepository.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/service/SearchService.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/util/ElasticsearchUtil.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/util/IndexingUtil.kt
Labels: ✨ Feature, 📬 API

#6 [Feat] es 카테고리검색 기능 추가
  src/main/kotlin/marketnawa/be/ott/marketnawabe/common/ResponseDTO.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/controller/SearchController.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/service/SearchService.kt
  src/main/kotlin/marketnawa/be/ott/marketnawabe/util/ElasticsearchUtil.kt
Labels: ✨ Feature, 🔨 Refactor
